### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by 15399240803** [Mereep/keel_csv#1]
csv file is not real data. like this.
![image](https://user-images.githubusercontent.com/63033258/202886033-65ffd09c-cee6-43f5-adcb-71ff0537794c.png)

**Comment by Mereep** [comment]
Hello. Due to the size those files are handled via a git extension (`git-lfs`; git large file system). You may need to install it first on your machine. For example see here: https://www.atlassian.com/git/tutorials/git-lfs

**Comment by 15399240803** [comment]
OK，Thank you.
